### ISSUE TITLE
Availability of slides in future.

### ISSUE THREAD

**Issue by chirag200666** [HydPy/PyConf17Slides#3]
What if the slides get deleted, unshared from the current sources.
I think it will be good to keep a copy in this repo as well.

@manitha @ananyo2012 @inovizz 
What are your thoughts?

**Comment by inovizz** [comment]
Yes, that's a good idea. I thought of doing the same but kushal's slide is not downloadable so kept it this way. However, I'll go ahead and create a folder inside this repo and dump all downloaded files.

**Comment by ananyo2012** [comment]
@inovizz @chirag200666 I have added all the slides in a Slides folder in the Repo. Ideally we should also link to the slides in the repo.

**Comment by ananyo2012** [comment]
@chirag200666 Can you enable gh-pages for this repo in the master branch if you have admin access ?

**Comment by ananyo2012** [comment]
Closing this issue. All slides have been downloaded in the slides folder and links to them have been properly placed.
